force-app/main/default/objects/VRT_Rental__c/VRT_Rental__c.object-meta.xml
<CustomObject>
    <description>Realiza el seguimiento de las operaciones de alquiler de los vehículos de la flota de la empresa.</description>
    <label>Alquiler</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alquiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquileres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Este campo de la lista de selección indicará el estado del alquiler.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_TRG_RentalHandler.cls
/**
 * @author		AMADRIDN (NTT Data)
 * @since		04/04/2024
 * @desc		Handler class for trigger VRT_TRG_Rental
 * @history		04/04/2024 - AMADRIDN - Created class
 * 				08/04/2024 - AMADRIDN - Added comments
 * 				12/04/2024 - AMADRIDN - Added onAfterUpdate
 */
public class VRT_TRG_RentalHandler 
{
    /**
     * @desc	After Insert Handler
     * @param	triggerNew: list of rentals inserted
     */
    public void onAfterInsert(List<VRT_Rental__c> triggerNew)
    {
        VRT_TRG_RentalHandlerHelper.updateConditionVehicle(triggerNew);
    }
    
    /**
     * @desc	After Update Handler
     * @param	oldMap: map with rentals in old state 
     * @param	newMap: map with rentals in new state 
     */
    public void onAfterUpdate(Map<Id, VRT_Rental__c> oldMap, Map<Id, VRT_Rental__c> newMap)
    {
        VRT_TRG_RentalHandlerHelper.updateVehicleRentalCompleted(oldMap, newMap);

        Set<Id> completedRentalIds = new Set<Id>();
        for (Id rentalId : newMap.keySet())
        {
            if (oldMap.get(rentalId).VRT_SEL_Status__c != 'Completado' && newMap.get(rentalId).VRT_SEL_Status__c == 'Completado')
                completedRentalIds.add(rentalId);
        }
        if (!completedRentalIds.isEmpty())
            System.enqueueJob(new VRT_InvoicingQueueable(completedRentalIds));
    }

    /**
     * @desc	Before Insert Handler
     * @param	triggerNew: list of rentals to be inserted
     */
    public void onBeforeInsert(List<VRT_Rental__c> triggerNew) 
    {
        VRT_PricingEngineService.calculateTotalCost(triggerNew);
        VRT_AvailabilityService.checkOverlaps(triggerNew);
    }

    /**
     * @desc	Before Update Handler
     * @param	oldMap: map with rentals in old state 
     * @param	newMap: map with rentals in new state 
     */
    public void onBeforeUpdate(Map<Id, VRT_Rental__c> oldMap, Map<Id, VRT_Rental__c> newMap)
    {
        VRT_PricingEngineService.calculateTotalCost(newMap.values());
        VRT_AvailabilityService.checkOverlaps(newMap.values());
    }
}